// <auto-generated />
using System;
using InventarioWeb.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventarioWeb.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260704201716_DatosPruebaSeedData")]
    partial class DatosPruebaSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HistorialPrecio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Motivo")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PrecioCostoAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrecioCostoNuevo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVentaAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVentaNuevo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCambio")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FechaCambio");

                    b.HasIndex("ProductoId");

                    b.ToTable("HistorialPrecios");
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.Almacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Encargado")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Almacenes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "ALM-CENTRAL",
                            Direccion = "Calle Principal #100",
                            Encargado = "Carlos López",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8557),
                            Nombre = "Almacén Central",
                            Telefono = "555-0101",
                            Tipo = "ALMACEN"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Codigo = "MER-NORTE",
                            Direccion = "Av. Norte #200",
                            Encargado = "María García",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8562),
                            Nombre = "Mercado Norte",
                            Telefono = "555-0202",
                            Tipo = "MERCADO"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Codigo = "MER-SUR",
                            Direccion = "Av. Sur #300",
                            Encargado = "Pedro Martínez",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8566),
                            Nombre = "Mercado Sur",
                            Telefono = "555-0303",
                            Tipo = "MERCADO"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Codigo = "MER-ESTE",
                            Direccion = "Calle Este #400",
                            Encargado = "Ana Rodríguez",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8571),
                            Nombre = "Mercado Este",
                            Telefono = "555-0404",
                            Tipo = "MERCADO"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Codigo = "ALM-SEC",
                            Direccion = "Zona Industrial #500",
                            Encargado = "Luis Sánchez",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8575),
                            Nombre = "Almacén Secundario",
                            Telefono = "555-0505",
                            Tipo = "ALMACEN"
                        });
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Dispositivos electrónicos y gadgets",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8159),
                            Nombre = "Electrónicos"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Muebles de oficina y hogar",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8164),
                            Nombre = "Muebles"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Suministros de oficina y papelería",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8168),
                            Nombre = "Suministros"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Productos alimenticios y bebidas",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8171),
                            Nombre = "Alimentos"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Productos de limpieza e higiene",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8175),
                            Nombre = "Limpieza"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Herramientas y materiales de construcción",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8178),
                            Nombre = "Ferretería"
                        });
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.Consignacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("AlmacenOrigenId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroConsignacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("VendedorContacto")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("VendedorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("VendedorTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenOrigenId");

                    b.HasIndex("NumeroConsignacion")
                        .IsUnique();

                    b.ToTable("Consignaciones");
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.ConsignacionDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CantidadDevuelta")
                        .HasColumnType("int");

                    b.Property<int>("CantidadEntregada")
                        .HasColumnType("int");

                    b.Property<int>("CantidadVendida")
                        .HasColumnType("int");

                    b.Property<int>("ConsignacionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsignacionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ConsignacionDetalles");
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("AlmacenDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("AlmacenOrigenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenDestinoId");

                    b.HasIndex("AlmacenOrigenId");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.MovimientoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MovimientoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovimientoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("MovimientoDetalles");
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("PrecioCosto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrecioVentaMayorista")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVentaMinorista")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnidadMedidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaId = 1,
                            Codigo = "ELE-001",
                            Descripcion = "Laptop HP 15.6 pulgadas, 8GB RAM, 256GB SSD",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8625),
                            Nombre = "Laptop HP 15\"",
                            PrecioCosto = 650.00m,
                            PrecioVentaMayorista = 799.99m,
                            PrecioVentaMinorista = 899.99m,
                            UnidadMedidaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaId = 1,
                            Codigo = "ELE-002",
                            Descripcion = "Monitor Dell 24 pulgadas Full HD",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8633),
                            Nombre = "Monitor Dell 24\"",
                            PrecioCosto = 200.00m,
                            PrecioVentaMayorista = 299.99m,
                            PrecioVentaMinorista = 349.99m,
                            UnidadMedidaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaId = 1,
                            Codigo = "ELE-003",
                            Descripcion = "Teclado inalámbrico Bluetooth multimedia",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8640),
                            Nombre = "Teclado Inalámbrico",
                            PrecioCosto = 25.00m,
                            PrecioVentaMayorista = 39.99m,
                            PrecioVentaMinorista = 49.99m,
                            UnidadMedidaId = 1
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaId = 1,
                            Codigo = "ELE-004",
                            Descripcion = "Mouse óptico USB ergonómico 1200dpi",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8646),
                            Nombre = "Mouse Óptico USB",
                            PrecioCosto = 10.00m,
                            PrecioVentaMayorista = 19.99m,
                            PrecioVentaMinorista = 24.99m,
                            UnidadMedidaId = 1
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CategoriaId = 1,
                            Codigo = "ELE-005",
                            Descripcion = "Audífonos inalámbricos con micrófono y cancelación de ruido",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8652),
                            Nombre = "Audífonos Bluetooth",
                            PrecioCosto = 35.00m,
                            PrecioVentaMayorista = 59.99m,
                            PrecioVentaMinorista = 79.99m,
                            UnidadMedidaId = 1
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CategoriaId = 2,
                            Codigo = "MUE-001",
                            Descripcion = "Escritorio de madera 120x60cm con cajones",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8658),
                            Nombre = "Escritorio Ejecutivo",
                            PrecioCosto = 250.00m,
                            PrecioVentaMayorista = 399.99m,
                            PrecioVentaMinorista = 499.99m,
                            UnidadMedidaId = 1
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CategoriaId = 2,
                            Codigo = "MUE-002",
                            Descripcion = "Silla ergonómica con soporte lumbar ajustable",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8663),
                            Nombre = "Silla de Oficina",
                            PrecioCosto = 150.00m,
                            PrecioVentaMayorista = 249.99m,
                            PrecioVentaMinorista = 299.99m,
                            UnidadMedidaId = 1
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CategoriaId = 2,
                            Codigo = "MUE-003",
                            Descripcion = "Estantería 5 niveles 180x90x40cm",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8668),
                            Nombre = "Estantería Metálica",
                            PrecioCosto = 100.00m,
                            PrecioVentaMayorista = 159.99m,
                            PrecioVentaMinorista = 199.99m,
                            UnidadMedidaId = 1
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            CategoriaId = 2,
                            Codigo = "MUE-004",
                            Descripcion = "Archivador metálico con llave de seguridad",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8673),
                            Nombre = "Archivador 3 Cajones",
                            PrecioCosto = 80.00m,
                            PrecioVentaMayorista = 129.99m,
                            PrecioVentaMinorista = 159.99m,
                            UnidadMedidaId = 1
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            CategoriaId = 3,
                            Codigo = "SUM-001",
                            Descripcion = "Resma de papel bond A4 500 hojas 75g",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8678),
                            Nombre = "Papel Bond A4",
                            PrecioCosto = 3.50m,
                            PrecioVentaMayorista = 5.99m,
                            PrecioVentaMinorista = 7.99m,
                            UnidadMedidaId = 5
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            CategoriaId = 3,
                            Codigo = "SUM-002",
                            Descripcion = "Caja de 12 bolígrafos azules punto fino",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8683),
                            Nombre = "Bolígrafos Azules",
                            PrecioCosto = 2.00m,
                            PrecioVentaMayorista = 3.99m,
                            PrecioVentaMinorista = 4.99m,
                            UnidadMedidaId = 5
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            CategoriaId = 3,
                            Codigo = "SUM-003",
                            Descripcion = "Cuaderno 100 hojas rayado tamaño carta",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8688),
                            Nombre = "Cuaderno Universitario",
                            PrecioCosto = 1.50m,
                            PrecioVentaMayorista = 2.99m,
                            PrecioVentaMinorista = 3.99m,
                            UnidadMedidaId = 1
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            CategoriaId = 3,
                            Codigo = "SUM-004",
                            Descripcion = "Cartucho de tinta negra compatible HP",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8694),
                            Nombre = "Tinta para Impresora",
                            PrecioCosto = 15.00m,
                            PrecioVentaMayorista = 24.99m,
                            PrecioVentaMinorista = 34.99m,
                            UnidadMedidaId = 1
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            CategoriaId = 3,
                            Codigo = "SUM-005",
                            Descripcion = "Cinta adhesiva transparente 12mm x 33m",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8699),
                            Nombre = "Cinta Adhesiva",
                            PrecioCosto = 0.50m,
                            PrecioVentaMayorista = 0.99m,
                            PrecioVentaMinorista = 1.49m,
                            UnidadMedidaId = 8
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            CategoriaId = 4,
                            Codigo = "ALI-001",
                            Descripcion = "Café molido premium 500g",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8703),
                            Nombre = "Café Molido",
                            PrecioCosto = 8.00m,
                            PrecioVentaMayorista = 11.99m,
                            PrecioVentaMinorista = 14.99m,
                            UnidadMedidaId = 1
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            CategoriaId = 4,
                            Codigo = "ALI-002",
                            Descripcion = "Azúcar blanca refinada 1Kg",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8708),
                            Nombre = "Azúcar Blanca",
                            PrecioCosto = 1.00m,
                            PrecioVentaMayorista = 1.99m,
                            PrecioVentaMinorista = 2.49m,
                            UnidadMedidaId = 2
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            CategoriaId = 4,
                            Codigo = "ALI-003",
                            Descripcion = "Botella de agua mineral sin gas 500ml",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8714),
                            Nombre = "Agua Mineral",
                            PrecioCosto = 0.30m,
                            PrecioVentaMayorista = 0.75m,
                            PrecioVentaMinorista = 0.99m,
                            UnidadMedidaId = 1
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            CategoriaId = 4,
                            Codigo = "ALI-004",
                            Descripcion = "Paquete de galletas surtidas 400g",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8719),
                            Nombre = "Galletas Surtidas",
                            PrecioCosto = 2.50m,
                            PrecioVentaMayorista = 3.99m,
                            PrecioVentaMinorista = 4.99m,
                            UnidadMedidaId = 1
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            CategoriaId = 5,
                            Codigo = "LIM-001",
                            Descripcion = "Detergente líquido multiusos 1L",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8725),
                            Nombre = "Detergente Líquido",
                            PrecioCosto = 2.00m,
                            PrecioVentaMayorista = 3.99m,
                            PrecioVentaMinorista = 4.99m,
                            UnidadMedidaId = 3
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            CategoriaId = 5,
                            Codigo = "LIM-002",
                            Descripcion = "Cloro concentrado 1L",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8730),
                            Nombre = "Cloro Concentrado",
                            PrecioCosto = 1.00m,
                            PrecioVentaMayorista = 1.99m,
                            PrecioVentaMinorista = 2.49m,
                            UnidadMedidaId = 3
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            CategoriaId = 5,
                            Codigo = "LIM-003",
                            Descripcion = "Paquete de 4 rollos doble hoja",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8735),
                            Nombre = "Papel Higiénico",
                            PrecioCosto = 1.50m,
                            PrecioVentaMayorista = 2.99m,
                            PrecioVentaMinorista = 3.99m,
                            UnidadMedidaId = 5
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            CategoriaId = 5,
                            Codigo = "LIM-004",
                            Descripcion = "Jabón líquido antibacterial 500ml",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8740),
                            Nombre = "Jabón de Manos",
                            PrecioCosto = 2.00m,
                            PrecioVentaMayorista = 3.49m,
                            PrecioVentaMinorista = 4.49m,
                            UnidadMedidaId = 1
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            CategoriaId = 6,
                            Codigo = "FER-001",
                            Descripcion = "Martillo de acero forjado mango de madera",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8744),
                            Nombre = "Martillo de Acero",
                            PrecioCosto = 8.00m,
                            PrecioVentaMayorista = 12.99m,
                            PrecioVentaMinorista = 15.99m,
                            UnidadMedidaId = 1
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            CategoriaId = 6,
                            Codigo = "FER-002",
                            Descripcion = "Cinta métrica retráctil 5 metros",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8749),
                            Nombre = "Cinta Métrica 5m",
                            PrecioCosto = 3.00m,
                            PrecioVentaMayorista = 5.99m,
                            PrecioVentaMinorista = 7.99m,
                            UnidadMedidaId = 1
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            CategoriaId = 6,
                            Codigo = "FER-003",
                            Descripcion = "Cable eléctrico calibre 12 por metro",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8755),
                            Nombre = "Cable Eléctrico #12",
                            PrecioCosto = 0.50m,
                            PrecioVentaMayorista = 0.99m,
                            PrecioVentaMinorista = 1.49m,
                            UnidadMedidaId = 4
                        });
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RUC")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Direccion = "Av. Tecnológica #100",
                            Email = "ventas@techsupply.com",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8974),
                            Nombre = "TechSupply S.A.",
                            RUC = "12345678901",
                            Telefono = "555-1001"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Direccion = "Calle Carpinteros #200",
                            Email = "info@mueblesymas.com",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8978),
                            Nombre = "Muebles & Más",
                            RUC = "23456789012",
                            Telefono = "555-1002"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Direccion = "Av. Papel #300",
                            Email = "pedidos@distpapelera.com",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8981),
                            Nombre = "Distribuidora Papelera",
                            RUC = "34567890123",
                            Telefono = "555-1003"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Direccion = "Zona Industrial #400",
                            Email = "contacto@alimentosdelsur.com",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8985),
                            Nombre = "Alimentos del Sur",
                            RUC = "45678901234",
                            Telefono = "555-1004"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Direccion = "Parque Industrial #500",
                            Email = "ventas@cleanpro.com",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8988),
                            Nombre = "CleanPro S.A.",
                            RUC = "56789012345",
                            Telefono = "555-1005"
                        });
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.StockAlmacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("AlmacenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<int>("StockMaximo")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenId");

                    b.HasIndex("ProductoId", "AlmacenId")
                        .IsUnique();

                    b.ToTable("StockAlmacenes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            AlmacenId = 1,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8841),
                            ProductoId = 1,
                            StockActual = 15,
                            StockMaximo = 30,
                            StockMinimo = 5,
                            Ubicacion = "A-01"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            AlmacenId = 1,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8845),
                            ProductoId = 2,
                            StockActual = 10,
                            StockMaximo = 20,
                            StockMinimo = 3,
                            Ubicacion = "A-02"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            AlmacenId = 1,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8849),
                            ProductoId = 3,
                            StockActual = 50,
                            StockMaximo = 100,
                            StockMinimo = 10,
                            Ubicacion = "A-03"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            AlmacenId = 1,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8853),
                            ProductoId = 4,
                            StockActual = 75,
                            StockMaximo = 150,
                            StockMinimo = 15,
                            Ubicacion = "A-03"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            AlmacenId = 1,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8856),
                            ProductoId = 5,
                            StockActual = 30,
                            StockMaximo = 60,
                            StockMinimo = 8,
                            Ubicacion = "A-04"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            AlmacenId = 1,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8860),
                            ProductoId = 6,
                            StockActual = 5,
                            StockMaximo = 10,
                            StockMinimo = 2,
                            Ubicacion = "B-01"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            AlmacenId = 1,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8864),
                            ProductoId = 7,
                            StockActual = 8,
                            StockMaximo = 15,
                            StockMinimo = 3,
                            Ubicacion = "B-02"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            AlmacenId = 1,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8867),
                            ProductoId = 8,
                            StockActual = 4,
                            StockMaximo = 8,
                            StockMinimo = 2,
                            Ubicacion = "B-03"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            AlmacenId = 1,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8872),
                            ProductoId = 9,
                            StockActual = 6,
                            StockMaximo = 12,
                            StockMinimo = 2,
                            Ubicacion = "B-04"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            AlmacenId = 2,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8876),
                            ProductoId = 1,
                            StockActual = 3,
                            StockMaximo = 10,
                            StockMinimo = 2,
                            Ubicacion = "E-01"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            AlmacenId = 2,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8879),
                            ProductoId = 2,
                            StockActual = 2,
                            StockMaximo = 5,
                            StockMinimo = 1,
                            Ubicacion = "E-02"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            AlmacenId = 2,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8883),
                            ProductoId = 4,
                            StockActual = 20,
                            StockMaximo = 40,
                            StockMinimo = 5,
                            Ubicacion = "E-03"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            AlmacenId = 2,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8886),
                            ProductoId = 19,
                            StockActual = 60,
                            StockMaximo = 120,
                            StockMinimo = 15,
                            Ubicacion = "L-01"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            AlmacenId = 2,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8890),
                            ProductoId = 20,
                            StockActual = 45,
                            StockMaximo = 90,
                            StockMinimo = 10,
                            Ubicacion = "L-02"
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            AlmacenId = 2,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8894),
                            ProductoId = 21,
                            StockActual = 90,
                            StockMaximo = 180,
                            StockMinimo = 20,
                            Ubicacion = "L-03"
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            AlmacenId = 3,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8897),
                            ProductoId = 10,
                            StockActual = 100,
                            StockMaximo = 200,
                            StockMinimo = 20,
                            Ubicacion = "S-01"
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            AlmacenId = 3,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8901),
                            ProductoId = 11,
                            StockActual = 80,
                            StockMaximo = 150,
                            StockMinimo = 15,
                            Ubicacion = "S-02"
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            AlmacenId = 3,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8904),
                            ProductoId = 12,
                            StockActual = 150,
                            StockMaximo = 300,
                            StockMinimo = 30,
                            Ubicacion = "S-03"
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            AlmacenId = 4,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8908),
                            ProductoId = 15,
                            StockActual = 25,
                            StockMaximo = 50,
                            StockMinimo = 5,
                            Ubicacion = "D-01"
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            AlmacenId = 4,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8911),
                            ProductoId = 16,
                            StockActual = 40,
                            StockMaximo = 80,
                            StockMinimo = 10,
                            Ubicacion = "D-02"
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            AlmacenId = 4,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8915),
                            ProductoId = 17,
                            StockActual = 200,
                            StockMaximo = 400,
                            StockMinimo = 50,
                            Ubicacion = "D-03"
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            AlmacenId = 4,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8918),
                            ProductoId = 18,
                            StockActual = 30,
                            StockMaximo = 60,
                            StockMinimo = 8,
                            Ubicacion = "D-04"
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            AlmacenId = 5,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8922),
                            ProductoId = 23,
                            StockActual = 12,
                            StockMaximo = 25,
                            StockMinimo = 3,
                            Ubicacion = "F-01"
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            AlmacenId = 5,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8925),
                            ProductoId = 24,
                            StockActual = 20,
                            StockMaximo = 40,
                            StockMinimo = 5,
                            Ubicacion = "F-02"
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            AlmacenId = 5,
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8929),
                            ProductoId = 25,
                            StockActual = 100,
                            StockMaximo = 200,
                            StockMinimo = 20,
                            Ubicacion = "F-03"
                        });
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UnidadesMedida");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abreviatura = "U",
                            Activo = true,
                            Descripcion = "Unidad individual",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8442),
                            Nombre = "Unidad"
                        },
                        new
                        {
                            Id = 2,
                            Abreviatura = "Kg",
                            Activo = true,
                            Descripcion = "Peso en kilogramos",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8447),
                            Nombre = "Kilogramo"
                        },
                        new
                        {
                            Id = 3,
                            Abreviatura = "L",
                            Activo = true,
                            Descripcion = "Volumen en litros",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8450),
                            Nombre = "Litro"
                        },
                        new
                        {
                            Id = 4,
                            Abreviatura = "m",
                            Activo = true,
                            Descripcion = "Longitud en metros",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8454),
                            Nombre = "Metro"
                        },
                        new
                        {
                            Id = 5,
                            Abreviatura = "Cja",
                            Activo = true,
                            Descripcion = "Caja o paquete cerrado",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8457),
                            Nombre = "Caja"
                        },
                        new
                        {
                            Id = 6,
                            Abreviatura = "Doc",
                            Activo = true,
                            Descripcion = "Conjunto de 12 unidades",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8461),
                            Nombre = "Docena"
                        },
                        new
                        {
                            Id = 7,
                            Abreviatura = "Par",
                            Activo = true,
                            Descripcion = "Conjunto de 2 unidades",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8465),
                            Nombre = "Par"
                        },
                        new
                        {
                            Id = 8,
                            Abreviatura = "Rol",
                            Activo = true,
                            Descripcion = "Rollo completo",
                            FechaCreacion = new DateTime(2026, 7, 4, 16, 17, 15, 973, DateTimeKind.Local).AddTicks(8468),
                            Nombre = "Rollo"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HistorialPrecio", b =>
                {
                    b.HasOne("InventarioWeb.Core.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.Consignacion", b =>
                {
                    b.HasOne("InventarioWeb.Core.Entities.Almacen", "AlmacenOrigen")
                        .WithMany()
                        .HasForeignKey("AlmacenOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlmacenOrigen");
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.ConsignacionDetalle", b =>
                {
                    b.HasOne("InventarioWeb.Core.Entities.Consignacion", "Consignacion")
                        .WithMany("Detalles")
                        .HasForeignKey("ConsignacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarioWeb.Core.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consignacion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.Movimiento", b =>
                {
                    b.HasOne("InventarioWeb.Core.Entities.Almacen", "AlmacenDestino")
                        .WithMany("MovimientosDestino")
                        .HasForeignKey("AlmacenDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InventarioWeb.Core.Entities.Almacen", "AlmacenOrigen")
                        .WithMany("MovimientosOrigen")
                        .HasForeignKey("AlmacenOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlmacenDestino");

                    b.Navigation("AlmacenOrigen");
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.MovimientoDetalle", b =>
                {
                    b.HasOne("InventarioWeb.Core.Entities.Movimiento", "Movimiento")
                        .WithMany("Detalles")
                        .HasForeignKey("MovimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarioWeb.Core.Entities.Producto", "Producto")
                        .WithMany("MovimientosDetalle")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movimiento");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.Producto", b =>
                {
                    b.HasOne("InventarioWeb.Core.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventarioWeb.Core.Entities.UnidadMedida", "UnidadMedida")
                        .WithMany("Productos")
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.StockAlmacen", b =>
                {
                    b.HasOne("InventarioWeb.Core.Entities.Almacen", "Almacen")
                        .WithMany("Stocks")
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventarioWeb.Core.Entities.Producto", "Producto")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("InventarioWeb.Core.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InventarioWeb.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InventarioWeb.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("InventarioWeb.Core.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventarioWeb.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InventarioWeb.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.Almacen", b =>
                {
                    b.Navigation("MovimientosDestino");

                    b.Navigation("MovimientosOrigen");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.Consignacion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.Movimiento", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.Producto", b =>
                {
                    b.Navigation("MovimientosDetalle");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("InventarioWeb.Core.Entities.UnidadMedida", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
